INSERT INTO esrbija.mestos (`naziv`, `created_at`, `updated_at`) -- umesto "esrbija" pisete nazvi vase baze
values 
('LAZAREVAC', now(), now()),
('LAJKOVAC', now(), now()),
('LAPOVO', now(), now()),
('LEBANE', now(), now()),
('LEPOSAVIĆ', now(), now()),
('LESKOVAC', now(), now()),
('LIPLJAN', now(), now()),
('LOZNICA', now(), now()),
('LUČANI', now(), now()),
('LJIG', now(), now()),
('LJUBOVIJA', now(), now()),
('MAJDANPEK', now(), now()),
('MALI ZVORNIK', now(), now()),
('MALI IĐOŠ', now(), now()),
('MALO CRNIĆE', now(), now()),
('MEDVEĐA', now(), now()),
('MEDIANA', now(), now()),
('MEROŠINA', now(), now()),
('MIONICA', now(), now()),
('MLADENOVAC', now(), now()),
('NEGOTIN', now(), now()),
('NIŠKA BANJA', now(), now()),
('NOVA VAROŠ', now(), now()),
('NOVA CRNJA', now(), now()),
('NOVI BEOGRAD', now(), now()),
('NOVI BEČEJ', now(), now()),
('NOVI KNEŽEVAC', now(), now()),
('NOVI PAZAR', now(), now()),
('NOVI SAD', now(), now()),
('NOVO BRDO', now(), now()),
('OBILIĆ', now(), now()),
('OBRENOVAC', now(), now()),
('OPOVO', now(), now()),
('ORAHOVAC', now(), now()),
('OSEČINA', now(), now()),
('ODŽACI', now(), now()),
('PALILULA', now(), now()),
('PALILULA-NIŠ', now(), now()),
('PANTELEJ', now(), now()),
('PANČEVO', now(), now()),
('PARAĆIN', now(), now()),
('PETROVARADIN', now(), now()),
('PETROVAC NA MLAVI', now(), now()),
('PEĆ', now(), now()),
('PEĆINCI', now(), now()),
('PIROT', now(), now()),
('PLANDIŠTE', now(), now()),
('PODUJEVO', now(), now()),
('POŽAREVAC', now(), now()),
('POŽEGA', now(), now()),
('PREŠEVO', now(), now()),
('PRIBOJ', now(), now()),
('PRIZREN', now(), now()),
('PRIJEPOLJE', now(), now()),
('PRIŠTINA', now(), now()),
('PROKUPLJE', now(), now()),
('RAŽANJ', now(), now()),
('RAKOVICA', now(), now()),
('RAČA', now(), now()),
('RAŠKA', now(), now()),
('REKOVAC', now(), now()),
('RUMA', now(), now()),
('SAVSKI VENAC', now(), now()),
('SVILAJNAC', now(), now()),
('SVRLJIG', now(), now()),
('SENTA', now(), now()),
('SEČANJ', now(), now()),
('SJENICA', now(), now()),
('SMEDEREVO', now(), now()),
('SMEDEREVSKA PALANKA', now(), now()),
('SOKO BANJA', now(), now()),
('SOMBOR', now(), now()),
('SOPOT', now(), now()),
('SRBICA', now(), now()),
('SRBOBRAN', now(), now()),
('SREMSKA MITROVICA', now(), now()),
('SREMSKI KARLOVCI', now(), now()),
('STARA PAZOVA', now(), now()),
('STARI GRAD', now(), now()),
('STRAGARI', now(), now()),
('SUBOTICA', now(), now()),
('SUVA REKA', now(), now()),
('SURDULICA', now(), now()),
('SURČIN', now(), now()),
('TEMERIN', now(), now()),
('TITEL', now(), now()),
('TOPOLA', now(), now()),
('TRGOVIŠTE', now(), now()),
('TRSTENIK', now(), now()),
('TUTIN', now(), now()),
('ĆIĆEVAC', now(), now()),
('ĆUPRIJA', now(), now()),
('UB', now(), now()),
('UŽICE', now(), now()),
('UROŠEVAC', now(), now()),
('CRVENI KRST -NIŠ', now(), now()),
('CRNA TRAVA', now(), now()),
('ČAJETINA', now(), now()),
('ČAČAK', now(), now()),
('ČOKA', now(), now()),
('ČUKARICA', now(), now()),
('ŠABAC', now(), now()),
('ŠID', now(), now()),
('ŠTIMLJE', now(), now()),
('ŠTRPCE', now(), now()),
('GRAD BEOGRAD', now(), now()),
('REPUBLIKA SRBIJA', now(), now()),
('GRAD NOVI SAD', now(), now()),
('AP VOJVODINA', now(), now()),
('GRAD NIŠ', now(), now()),
('GRAD KRAGUJEVAC', now(), now()),
('GRAD PRIŠTINA', now(), now()),
('AP KOSOVO I METOHIJA', now(), now());

select * from esrbija.mestos;